apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoojun-deploy
  namespace: yoojun
  labels:
    app: yoojun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoojun
  template:
    metadata:
      labels:
        app: yoojun
    spec:
      imagePullSecrets:
       - name: ghcr-login-secret
      containers:
      - name: yoojun
        image: ghcr.io/ghddbwns9808/flux-template:image-REPLACEME
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
