apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yoojun-kustom
  namespace: yoojun
spec:
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    kind: OCIRepository
    name: yoojun-oci-repo
  targetNamespace: yoojun