apiVersion: v1
kind: Service
metadata:
  name: yoojun-service
  namespace: yoojun
  labels:
    app: yoojun
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: yoojun