name: Deploy Flux YAML to OCI

on:
  workflow_run:
    workflows: [ "Build and Push App Image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: .*|image: ghcr.io/ghddbwns9808/flux-template:image-${{ github.sha }}|" k8s/deployment.yaml

      - name: Install ORAS v1.1.0
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_1.1.0_linux_amd64.tar.gz -C oras-install/
          mv oras-install/oras ./oras

      - name: Create tar.gz of manifests
        run: |
          tar -czf flux-kustomize.tar.gz -C k8s .

      - name: Login to GHCR for ORAS
        run: |
          echo "${{ secrets.YOOJUN_SECRET }}" | ./oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR via ORAS
        run: |
          ./oras push ghcr.io/ghddbwns9808/flux-template:kustomize-latest \
            --artifact-type application/vnd.cncf.flux.kustomize.layer.v1 \
            flux-kustomize.tar.gz:application/gzip

      - name: Clean up tar
        run: rm -f flux-kustomize.tar.gz